### ISSUE TITLE
pip installation failed

### ISSUE THREAD

**Issue by asschweizer** [SBentley/qvd-utils#13]
Hey guys,
I was very happy to found this project. Unfortunately there is an issue on my OS X with Python 3.8.10

pip install qvd
ERROR: Could not find a version that satisfies the requirement qvd (from versions: none)
ERROR: No matching distribution found for qvd

Any ideas?

Best regards,
Axel

**Comment by agroideas** [comment]
Hi, I have the same problem, are you using a Mac with Apple Silicon processor?
Seems that there is a compatibilty problem with this.

**Comment by SBentley** [comment]
I have published the macOS wheels for the latest version (0.0.14) . Pip installing should now work for apple silicon.

**Comment by agroideas** [comment]
Hi, sorry to bother with this again, but the error remains.
I have Python 3.9, looking at the wheels files I only find macos X86, none ARM.

Thanks a lot
